// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Analysis: typeof import('./src/components/analysisTask/Analysis.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    House: typeof import('./src/components/house/House.vue')['default']
    NewsIndex: typeof import('./src/components/news/NewsIndex.vue')['default']
    Resource: typeof import('./src/components/resource/resource.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WholeKunShan: typeof import('./src/components/kunshan/WholeKunShan.vue')['default']
  }
}

export {}
